### ISSUE TITLE
Does this package support ROS indigo on Ubuntu 14.04?

### ISSUE THREAD

**Issue by danendrasingh** [mitll-ros-pkg/razor_imu_m0_driver#1]
Does this package support ROS indigo on Ubuntu 14.04? 
In addition, what will be the calibration procedure for the IMU?  Will it be same as one mentioned on sparkfun website?

**Comment by mboulet** [comment]
The package should work on ROS indigo on Ubuntu 14.04.

The factory_firmware_node does not accept any calibration parameters as it publishes the values reported by the sensor without additional manipulation [(per REP-145](https://github.com/ros-infrastructure/rep/blob/d50ef84bee3638bb053f87c31aeb1d449879b14d/rep-0145.rst))*. Therefore, any calibration should be performed and provided to downstream filtering or similar nodes, per the procedures of any such downstream nodes.

*Technically the hardware device can accept calibration parameters, which could be compliant with REP-145 as REP-145 only requires that the node not manipulate the data. however, the factory-programmed firmware does not provide a mechanism for setting the hardware calibration parameters.
